version: 2.1

orbs:
  # https://circleci.com/developer/orbs/orb/circleci/aws-s3
  aws-s3: circleci/aws-s3@2.0.0

jobs:
  build:
    docker:
      - image: cimg/node:17.9.0

    steps:
      - checkout

      # Download and cache dependencies. Use the latest cache
      # if no exact match is found.
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run:
          name: Installing dependencies
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: Building
          command: yarn build

      - aws-s3/sync:
          aws-region: AWS_DEFAULT_REGION
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          from: public/
          to: "s3://public.nikhil.io/text-generator/"
          arguments: |
            --delete \
            --content-encoding 'gzip'
