version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:17.9.0

    steps:
      - checkout

      # Download and cache dependencies. Use the latest cache
      # if no exact match is found.
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
            - v2-dependencies-

      - run:
          name: Installing dependencies
          command: yarn

      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

      - run:
          name: Building
          command: yarn build

      - run:
          name: Deploying
          command: aws s3 sync --delete public/ s3://public.nikhil.io/text-generator/
